security:
    encoders:
        gdm\UserBundle\Entity\User: sha512


    providers:
        main:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: .*
            anonymous: true
            provider:  main
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                default_target_path: /home
            logout:
                path: fos_user_security_logout
                target: /home
            remember_me:
                key: %secret%

    role_hierarchy:
        ROLE_USER: ROLE_USER
        ROLE_ADMIN:
            - ROLE_ADMIN
            - ROLE_USER
    access_control:
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/ajouter, role: ROLE_ADMIN }
        - { path: ^/ajouter_boutique, role: ROLE_ADMIN }
        - { path: ^/ajouter_maison, role: ROLE_ADMIN }
