parameters:
#    gdm_reservation.example.class: gdm\ReservationBundle\Example

services:
#    gdm_reservation.example:
#        class: %gdm_reservation.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
