<?php

namespace gdm\ReservationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * sejourRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class sejourRepository extends EntityRepository
{
}
