<?php

namespace gdm\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * descriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class descriptionRepository extends EntityRepository
{
}
