parameters:
#    gdm_admin.example.class: gdm\AdminBundle\Example

services:
#    gdm_admin.example:
#        class: %gdm_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
